# h2 configuration
# See https://github.com/dcosson/h2 for documentation.
#
# users:
#   yourname:
#     bridges:
#       telegram:
#         bot_token: "123456:ABC-DEF"
#         chat_id: 789
#       macos_notify:
#         enabled: true
